### ISSUE TITLE
Cannot load images in image viewer - ImageUtilities

### ISSUE THREAD

**Issue by loskirailaite** [mwittrien/BetterDiscordAddons#1481]
Images in the Image Viewer don't load since the last update. In the normal chat all images appear normally. Discord Stable
![image](https://user-images.githubusercontent.com/101947363/159134660-0dcc02f4-fa22-49cf-9b58-3787c05891cb.png)

**Comment by Drflash55** [comment]
Since I don't want to create duplicate issues, I'll just write out the details for him here.

**Describe the bug**
As of the latest version, images now fail to load properly when clicked on. Previews work properly.

**To Reproduce**
Happens when you click on any image to get a bigger preview.

**Expected behavior**
Image should appear normally.

**Screenshots**
Above screenshot shows the issue.

**Discord Build (stable, ptb or canary):**
Stable 119880 (2e39d24)
BetterDiscord 1.5.2

**Additional context**
Last version worked just fine, this one seems to be having issues. CTRL + R does not fix the issue either.
