### ISSUE TITLE
JoinedAtDate only pops up when you open the profile

### ISSUE THREAD

**Issue by Liz-chan** [mwittrien/BetterDiscordAddons#160]
With CreationDate, when you click on a profile it says it there immediately without it having to render, but with JoinedAtDate, you can see it popping up when you click on a profile, which is kind of annoying. It happens every time you click on a new profile.

EDIT: Also I've noticed that CreationDate always starts immediately when you restart Discord, but JoinedAtDate, ServerHider, and ShowHiddenChannels (just some of the plugins I have) take around 30 seconds to start up when I restart sometimes.

**Comment by mwittrien** [comment]
Date for JoinedAtDate has to be fetched from discord servers thats why it takes a sec for the first time you click on a new profile, this can not be fixed

plugins (except for the first one) taking 30 seconds to load on startup is also normal because the first plugin loads the lib and the other plugins have a delay to make sure the lib is loaded

**Comment by Liz-chan** [comment]
Ah ok, thanks for the explanation.
