### ISSUE TITLE
Sections being hidden

### ISSUE THREAD

**Issue by Cipher3569** [mwittrien/BetterDiscordAddons#1608]
when you hit the top of a category to minimize it the category goes away and there's no way to make it come back

**Comment by Meredith666** [comment]
I have the same problem

**Comment by Cipher3569** [comment]
> I have the same problem
Well lets hope the developer fixes the problem soon

**Comment by Meredith666** [comment]
do you also experience that discord freezes? It happened when I called with somebody after like 30 minutes the entire discord froze, but i still heard them but I couldnt like click on anything so only quiting the discord worked for me.I think its happening because of that plugin never happened before

**Comment by Cipher3569** [comment]
> do you also experience that discord freezes? It happened when I called with somebody after like 30 minutes the entire discord froze, but I still heard them but I couldn't like click on anything so only quitting the discord worked for me. I think its happening because of that plugin never happened before

Have you tried to repair better discord? mine has done that before but after I re installed better discord it worked just fine

**Comment by mwittrien** [comment]
#1606
