### ISSUE TITLE
[IMPROVEMENT] - Bring Back ShowHiddenChannels

### ISSUE THREAD

**Issue by JimmyHoke** [mwittrien/BetterDiscordAddons#1766]
ShowHiddenChannels should be brought back,  It was an amazing tool that revealed what channels your friends were hiding behind your back. It made discord a better, more transparent place. The deletion and non-consensual removal from its user's computers was, quite frankly, an appalling violation of the principles of free, open source software. While you have no obligation to continue development, you have no right to delete things from other's machines.

**Comment by evoke9** [comment]
While I don't agree with it's removal at all, it isn't because he didn't want to continue developing it. Betterdiscord is implementing new guidelines and part of it is them banning plugins that show hidden channels. I am sure someone will make a "black market" version, but I would be voicing my anger at the Betterdiscord team not mwittrien.

**Comment by Bananaman811** [comment]
I think it's unfair for them to be pushing this, I'm trying to find a workaround. I've downgraded everything other than better discord itself, have just showhidden channels and his dependency plugin running and it will not work. I think better discord itself is blocking this plugin
