### ISSUE TITLE
Folders keep disappearing/cannot create new folders

### ISSUE THREAD

**Issue by galaxyinfinitum** [mwittrien/BetterDiscordAddons#192]
So about 30 minutes ago, the serverfolders just all....disappeared. Leaving me with the vanilla list of servers. It's happened to me before, so I just tried to remake the folders and move on like I had in the past. But I can't make new folders. I click it and the menu doesn't pop up. None of my other folders exist anymore either. I deleted/reinstalled both bandage and serverfolders 3 different times, restarted discord, restarted my computer, etc. I'm not sure what to do at this point tbh.

**Comment by kzisme** [comment]
Please see https://github.com/mwittrien/BetterDiscordAddons/issues/191

**Comment by squidkidpaul** [comment]
Can confirm Discord Stable, build 36215 breaks the ServerFolders plugin

**Comment by TheDarkBomber** [comment]
@mwittrien

**Comment by TheDarkBomber** [comment]
They also fucked up the CSS a lot...

**Comment by mwittrien** [comment]
The plugin is broken

TheDarkBomber <notifications@github.com> schrieb am Mi., 24. Apr. 2019,
16:26:

**Comment by rtm516** [comment]
@mwittrien Any ETA on when this will get fixed since it seems to have wiped my folders so I cant sort them, unless you could send me an example config for me to manually edit the JSON. The error I get in console is:
[BDFDB] guild not found in BDFDB.DiscordClasses
e.(anonymous function) @ 5c074bd3a418f633840a.js:49
BDFDB.getDiscordClass @ BDFDB.js:1
get @ BDFDB.js:1
createNewFolder @ C:\Users\ryant\AppData\Roaming\BetterDiscord\plugins\ServerFolders.plugin.js:842
createitem.addEventListener @ C:\Users\ryant\AppData\Roaming\BetterDiscord\plugins\ServerFolders.plugin.js:474
i @ 5c074bd3a418f633840a.js:49

**Comment by ChildishGiant** [comment]
I've tried updating but it still seems broken. 
![image](https://user-images.githubusercontent.com/13716824/56750191-228fd280-677b-11e9-8fbb-595b31dc4d40.png)

**Comment by mwittrien** [comment]
Because it is still broken, a little patience jeez

Allie <notifications@github.com> schrieb am Do., 25. Apr. 2019, 17:57:

**Comment by ChildishGiant** [comment]
Oh I assumed since you closed the issue, the issue was fixed.
