### ISSUE TITLE
[BUG] ALL PLUGINS USING BDFDB ARE BROKEN (FIX ON 21ST NOV)

### ISSUE THREAD

**Issue by mwittrien** [mwittrien/BetterDiscordAddons#2047]
Yes i am aware that plugins that use BDFDB Library, so all of my plugins, are partially broken

I am on **vacation** until the **21st of november** _without_ my laptop so no fixes until then

Any plugin issue reports related to this issue will be locked and closed immediatly

**Comment by SliceTheDuck** [comment]
Enjoy ur vacation

**Comment by ChapperNi** [comment]
have a nice relaxation king

**Comment by ChickChuck2** [comment]
relaxa e goza

**Comment by oofish8888** [comment]
now that you are back, can you fix it?

**Comment by oofish8888** [comment]
dang it my bad

**Comment by Aholicknight** [comment]
> now that you are back, can you fix it?

@oofish8888 Give @mwittrien some time as he just got back. No need to rush excellence.

**Comment by IsaMorphic** [comment]
I just wanna express that I'm thankful to DevilBro for putting up with everyone's crap and still committing to fixing the issues, lol

**Comment by PhoenixGhost141** [comment]
Fix?

**Comment by DaniTarot** [comment]
He just back from Vacation, Don't hound the poor dude who is making you FREE plugins to improve your discord to immediately hop off his vacation and rush to his home laptop.

**Comment by oofish8888** [comment]
> > now that you are back, can you fix it?
> 
> @oofish8888 Give @mwittrien some time as he just got back. No need to rush excellence.

I only made the mistake of assuming that he was back, since the date was the 21st of November, exactly when he said he would come back from his vacation. However, I said "My Bad" after he told us that he wouldn't be back until 4 pm EST and so I realized my mistake. This is what people have to say to me. I patiently waited until 4 pm EST, when shortly after, he fixed the plugins. What's the problem here? Why do you people have to say this bullcrap to me?
