### ISSUE TITLE
[BUG] - DisplayServersAsChannels - Server Groups become stuck open

### ISSUE THREAD

**Issue by Renari** [mwittrien/BetterDiscordAddons#2461]
**Describe the bug**
It seems that some server groups can get stuck in the open state and can no longer be closed once opened. 

**To Reproduce**
When opening a server folder, the folder will disappear and no longer be able to be closed.

**Expected behavior**
To be able to open and close the server folder.

**Screenshots**
Example of one such group in the suck open state, notice how the group banner is now gone preventing it from being closed.
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/1839179/84eeba25-bd5a-479d-8674-ae36a7ec4a73)

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
The only commonality I've found between the groups that have this issue is they end in an `s` but that is very odd and it doesn't happen for every group that ends in an `s`. Changing one folder group name from `Streamers` to `Streamer` did make it stop happening, although this is just anecdotal evidence.

**Comment by null-zero** [comment]
Additional information: Changing the server folder color seems to fix the bug for the specific recolored folder

**Comment by mwittrien** [comment]
can yo utake a video? i can't reproduce it

also try it with ONLY DisplayServersAsChannels enabled

**Comment by null-zero** [comment]
With only the DisplayServersAsChannels plugin enabled, it still occurs, just to a lesser degree. The server folder icon and text disappear, and the element size changes. If you click the right area it will shrink the folder. With other plugins enabled, the elements click-box gets hidden by other elements presumably because of how small it ends up becoming.

Changing the color from the default folder color seems to fix the issue.

https://github.com/mwittrien/BetterDiscordAddons/assets/13855377/6467c70f-efe6-4289-9aaf-6914d1030a73
