### ISSUE TITLE
[BUG] - ImageUtilities

### ISSUE THREAD

**Issue by Venaf** [mwittrien/BetterDiscordAddons#2560]
**Describe the bug**
Client lag and eventual crash with ImageUtilities open.  

**To Reproduce**
Whenever ImageUtilities is enabled in mod list.  Channels with many emoji show the most lag and lead to Discord stalling completely and forcing itself to reload.

**Expected behavior**
No additional lag.

**Screenshots**
Screenshots really wouldn't help here.

**Discord Build (stable, ptb or canary):**
stable

**Additional context**
I've had this issue for multiple years now and never realized ImageUtilities was the one causing it - only discovered it after the most recent discord update breaking BetterDiscord when re-enabling mods to test.

**Comment by mwittrien** [comment]
Channels lagging when a lot of emojis are loaded, is an issue with base discord, since emojis are svgs, this even was a well known bug where spamming :chains: would lead discord to crash

the plugin doesn't interact with emojis in any way, so there is no reason why the plugin should cause such issues
