### ISSUE TITLE
GoogleTranslateOption -> If mention in message it wont translate

### ISSUE THREAD

**Issue by iiVeil** [mwittrien/BetterDiscordAddons#258]
If a mention of ANY kind is anywhere in the message the text wont translate; Maybe try finding <@ and removing ~13 characters after it? just giving an opinion on how to fix it

**Comment by mwittrien** [comment]
![44](https://user-images.githubusercontent.com/23700969/64004381-725a1e00-cb0e-11e9-9f01-c83a62ea62fd.gif)

Works jsut fien with mentions, if a text can not be translated then its due to Google not understanding what's being said or which language was used, thats a user error when ppl write in too gibbirish, nothing i can fix
