### ISSUE TITLE
[BUG] - CustomStatusPreset not working with new design

### ISSUE THREAD

**Issue by saitz** [mwittrien/BetterDiscordAddons#2758]
ye

**Comment by saitz** [comment]
"..right click custom status on new design" aint working either, no right click things happening

**Comment by mwittrien** [comment]
Screneshot your userpopup

**Comment by valo-io** [comment]
it used to work in the new design just a day ago or two, but today, right-clicking on the status doesn't bring up the status selection.
Can this be moved to the set status modal instead? like, adding a button right next to where we save the custom statuses? it would be super convenient and the load and save would always work as they're in the same spot.

**Comment by misterpyrrhuloxia** [comment]
The right-click on the new status bubble is finally working for me again after it had worked for all of a day or two a few days ago, but none of the emojis in my saved custom statuses are visible in the selection list. However, they _are_ still visible in the plugin's settings. Fortunately, they _do_ still work when I click on any of them, i.e. my status is still modified with the saved emoji, I just have to try to go by memory since I don't remember the position of most of my saved statuses.
And, as you can see below, I've got a whole ton of saved statuses, so trying to memorize their exact relative order would be stupid.
![image](https://github.com/user-attachments/assets/36252f49-1f97-4614-ba1e-f8c9e81d0156)

**Comment by misterpyrrhuloxia** [comment]
I've just submitted #2770 for this new invisible emoji problem.
