### ISSUE TITLE
[BUG] - ReadAllNotificationsButton missing read all button and inaccessible settings

### ISSUE THREAD

**Issue by xaenerys0** [mwittrien/BetterDiscordAddons#2802]
**Describe the bug**
Button to Read All is missing, can't access the settings either.

**To Reproduce**
Every time Discord is launched.

**Expected behavior**
Read All button should be available and settings for the plugin accessible.

**Screenshots**
![{3612AF13-C43A-4336-ABC1-ABC1F5667363}](https://github.com/user-attachments/assets/983e2fd8-ba45-4b20-b625-b2fb4695514d)
![{2B33162D-E0F8-483D-8001-B42A430F076D}](https://github.com/user-attachments/assets/1d4a07ba-6c88-4354-9b66-fc76a0c762b4)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
None

**Comment by Opius134** [comment]
Chiming in here to report, this bug seems to effect a lot of BDFDB plugins currently. 

![image](https://github.com/user-attachments/assets/a6428530-76ed-4916-b432-a282fcd5cd5f)
![image](https://github.com/user-attachments/assets/a6476ada-d5c6-4827-918d-61a9a141b68f)

It seems to stem from the latest BDFDB update, but rolling back doesn't seem to fix it.
