### ISSUE TITLE
[BUG] - ShowHiddenChannels

### ISSUE THREAD

**Issue by Farcrada** [mwittrien/BetterDiscordAddons#384]
**Describe the bug**
The new category that gets added is put in seemingly out of order. Don't know what to call it but the "draggable" attribute is made it's own div as a parent of the container. Compared to other categories that isn't correct (and makes manipulating an otherwise logical array tricky).

**To Reproduce**
n/a

**Expected behavior**
Integrated like the other categories.

**Screenshots**
![image](https://user-images.githubusercontent.com/8385001/76695292-dfce3600-667d-11ea-90cd-61847d5be07d.png)

**Discord Built (stable, ptb or canary):**
Stable 55975 

**Additional context**
n/a

**Comment by mwittrien** [comment]
1. It's not out of order, the "secret" category in BD2 is the first category
2. The channel/category item rendering is handled by Discord and not SHC, SHC simply inserts the channel/category data where it's usually removed
3. the div being an extra wrapper is caused by Discord as explained in 2., this happens whether SHC is enabled or not and has nothing to whether the category is usually hidden or not, only happens for the first category and doesn't happen for the first category in all cases

**Comment by mwittrien** [comment]
You can see this in the render function of the Category Wrapper Component

`var e = this.props,
t = e.channel,
n = e.muted,
r = e.connectChannelDragSource,
a = e.connectChannelDropTarget,
o = e.position,
i = e.sortingPosition,
l = e.collapsed,
u = e.hideIcon,
s = e.showTutorial,
c = M("div", {
	className: null != i ? o > i ? C.default.containerDragAfter : C.default.containerDragBefore : C.default.containerDefault
}, void 0, M(O.default, {
	className: C.default.iconVisibility,
	channel: t,
	muted: n,
	onClick: this.handleCollapseToggle,
	onContextMenu: this.handleContextMenu,
	collapsed: l,
	hideIcon: u || !1
}, void 0, this.renderCreateChannel()));
return s && (c = M("div", {}, void 0, M(d.default, {
	tutorialId: "organize-by-topic",
	position: d.TutorialIndicatorPositions.RIGHT,
	offsetY: 7
}, void 0, c))),
null != a && null != r ? a(r(c)) : c`

**Comment by Farcrada** [comment]
Got'cha, my apologies.
