### ISSUE TITLE
[BUG] - ForceImagePreviews not working most of the time

### ISSUE THREAD

**Issue by Jome666999** [mwittrien/BetterDiscordAddons#451]
**Describe the bug**
As I said in the title, ForceImagePreviews does not work most of the time. I have managed to get some images to embed by restarting the plugin, however that does not work all of the time. I have been testing this with tenor.com, media.discordapp.net, and prntscr.com links.

**To Reproduce**
Whenever a link is posted for a gif/image. Tried it with only ForceImagePreviews enabled, so it's not conflicting with any plugins.

**Expected behavior**
I expected it to embed the image/gif once a link was posted.

**Screenshots**
http://prntscr.com/tko1ij
(embedded links seem to remove the link now, so the screenshot would appear as though I just uploaded a gif rather than send a link, however that is not true because I did send it as a link)

**Discord Built (stable, ptb or canary):**
ptb

**Comment by mwittrien** [comment]
Several issues here

1. the link in you screenshot is not a direct link to an image file but a link to a tenor webpage with an image and more stuff, that's why the plugin doesn't recognizes it as such
2. it's neither an image nor a gif, it's a gifv which is a video disguised as a gif, the plugin doesn't try to force preview videos, because there are several issues that come with it
3. yes discord itself manages to embed the actual gifv via the link in your screenshot, but they handle such links server sided with several exxtra APIs from webpages like tenor and giphy which prove the actual gifv links and thumbnails and I don't have any idea how they do it since it's not open source
