### ISSUE TITLE
[BUG] - PluginRepo(or ThemeRepo?) - Bugged update bar as of 2020-09-23

### ISSUE THREAD

**Issue by polyzium** [mwittrien/BetterDiscordAddons#510]
**Describe the bug**
I just started Discord today (as of 2020-09-23T16:51:42+0000). Instead of an update notification, I see an empty grey bar and a bugged update notification.
I can't tell which Repo plugin is causing this.

**To Reproduce**
When a plugin/theme gets an update.

**Expected behavior**
A green bar with a list of plugins/themes that need to be updated a clickable update button

**Screenshots**
![image](https://user-images.githubusercontent.com/22579935/94044148-6eaece80-fdd6-11ea-838d-222be8529b1f.png)

**Discord Build (stable, ptb or canary):**
Stable.

**Additional context**
Updating the BBD injector did not fix the problem.
The plugin didn't have this problem yesterday (or at least the last time the plugins got updated).

**Comment by mwittrien** [comment]
None of those its caused by zerebos library

**Comment by arek-kwapis** [comment]
I believe this is caused by BDFBD from it's recent update (1.0.2), it introduced a new notification bar which seems to have broken for some reasons. The fix is to end discord either by quitting it via the Notification Libary or via Task Manager/Process Manager (Windows/Linux), and starting it back up again. Update Notifications will use the updated update bar from then on.

**Comment by mwittrien** [comment]
My lib is on 1.0.5 not 1.0.2

And my notice bar looks differently

**Comment by arek-kwapis** [comment]
> My lib is on 1.0.5 not 1.0.2
> 
> And my notice bar looks differently

My update bar looked differently from 1.0.2 onwards, rather than using the theme default bg it used a custom background, at which point other plugin notifications broke. Currently on 1.0.5 myself, with 1.0.4 using the same Update Notification bar as 1.0.2 used when the BORKage happened. As I said, It was different from 1.0.2 for me. Since there's no clear way to downgrade to earlier versions, I can't test them on my VM to 100% confirm.
