### ISSUE TITLE
[BUG] - ShowHiddenChannels Plugin Not Starting Properly

### ISSUE THREAD

**Issue by jqww** [mwittrien/BetterDiscordAddons#641]
**Describe the bug**
The hidden channels plugin will start, however, none of the hidden channels, show up, I then check the blacklist and make sure that it wasn't that, and it is not that

**To Reproduce**
Anytime that I start discord, the plugin starts, and nothing else happens

**Expected behavior**
The plugin runs, and has the plugin work as intended, and shows the hidden channels on the servers.

**Screenshots**

https://user-images.githubusercontent.com/53201564/106033026-d7fd6180-6096-11eb-9329-3522c425baa5.mp4

**Discord Built (stable, ptb or canary):**
Canary 75314 (fb194f3)
Host 1.0.21
Windows 10 64-Bit (10.0.18363)
Powercord v2 (9671e9c)

**Additional context**
Currently using BDcompat, for powercord, however in testing, every other plugin I use with BDcompat works perfectly fine, so I ruled that out.
Showed the Discord Testers discord, as there are MANY hidden channels on that server.

**Comment by mwittrien** [comment]
Due to interl changes done by discord on their canary build, almost all plugins are broken currently on canary

**Comment by mwittrien** [comment]
The temp fix provided by powercord for canary only barely makes powercord able to run, due to that a lot of plugins won't work because not all resources which were provided in the past are provided right now, you'll either need to wait till powercord releases a full fix for canary or wait till BD's fix is out
