### ISSUE TITLE
[QUESTION] Please read this through, it'd mean a lot to me and many others

### ISSUE THREAD

**Issue by kckarnige** [mwittrien/BetterDiscordAddons#744]
I know you don't want to be bothered with this, but I have a question that I've genuinely been having for you for a while now, why exactly don't you support Lightcord? Why go through the trouble of making your plugin library incompatible with it when it's just BandagedBD with a few extra features? The developers have no malicious intent whatsoever, and it doesn't have any signs of a TokenLogger or MessageLogger included with a clean install. It just personally boggles me why you would go through the trouble. I understand it isn't very stable, but that's why there's a Lightcord rewrite in development. Besides, you're kinda screwing people over by doing this, and I don't see it as fair, it should be the user's decision in the end, it is their responsibility after all to check what they're installing before installing it, especially when what they're doing is already against Discord ToS, ie. installing a 3rd party client modification.

**Comment by MoltenCoreDev** [comment]
big chungus nutsuck among sus

**Comment by aarav2you** [comment]
Do it yourself, it is the authors choice which platform they want to support, if you really want it there, then do it yourself. If you think its against Discord TOS then don't use it.

**Comment by mwittrien** [comment]
Why?
Maybe because they stole BDs code without asking?
Maybe because using a completly modified Discore client is a huge risk for users?
Maybe because Lightcords code base continously makes my Plugin not work nd ppl keep asking me without telling me they use Lightcord wasting a huge amount of my time on a daily basis?

I do not support it.
If ppl got the choice to choose what Client Mode they use then I got the choice to not make my stuff not working with it (which i am not even doing, its just a warning)

Btw i know for a fact that other plugin devs will make their stuff not work on Lightcord in the future
