### ISSUE TITLE
[Sound from blocked users is audible] - RemoveBlockedMessages

### ISSUE THREAD

**Issue by ant-killer** [mwittrien/BetterDiscordAddons#756]
-Bug description: there's a bug in the plugin 'RemoveBlockedMessages' where you can hear blocked users in voice-chats. This wasn't the case before.

-When: whenever I join a voice-chat.

-Expectation: them being muted since this was already a feature before the bug.

I use Stable

Extra context: I just hope it will be fixed as soon as possible because this plugin has helped me mentally. I no longer had to hear blocked users in voice chats. But now I can hear them and it bothers me a lot.

**Comment by mwittrien** [comment]
![cover](https://user-images.githubusercontent.com/23700969/115205265-aaeea700-a0f9-11eb-8c81-21a1f24a16c1.gif)
Works fine for me

As you can see in the gif my main account is blocked by my second account, he is first not muted because i unmuted him,
once he rejoins he is instantly muted locally on my side (I also tested this by me joining the VC with my main instead of my main joining when I am already in it, this also works just fine)

I disabled the option to hide users in the voice user list so you can actually see him getting muted
